/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ColorSwitch;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasRes() {
        String fileName =  "Assets/background.mpeg";
        ClassLoader classLoader = getClass().getClassLoader();
 
        File file = new File(classLoader.getResource(fileName).getFile());
         
        //File is found
        assertTrue(file.exists());
    }
}
